### ISSUE TITLE
FileNotFoundError: [WinError 2] can't find specified file

### ISSUE THREAD

**Issue by cyberpescadito** [dcrystalj/hdpiano#8]
Hello,

running on windows, i got this error: 
![image](https://user-images.githubusercontent.com/32546144/79687181-b6d52e00-8245-11ea-82fd-b4f7ddfc0e31.png)

sorry for the french, the translation should be something like: can't find specified file

i did modified line 39, without success, to:
`destination = 'C:\\users\\{0}\\.%(title)s.%(ext)s'.format(folder_name)`

Thanks for your precious help

**Comment by dcrystalj** [comment]
try this:
```
destination = 'C:\\Users\\Flo\\Documents\\Piano\\hdpiano-master\\%(title)s.%(ext)s'.format(folder_name)
```

and if line above doesn work, this:
```
destination = 'C:/Users/Flo/Documents/Piano/hdpiano-master/%(title)s.%(ext)s'
```

**Comment by cyberpescadito** [comment]
Still getting the same error message, also tried to open a cmd as admin and run the python without success. 
moved to C:\hdpiano-master to ensure this isn't a permission issue and still getting the same error message

**Comment by dcrystalj** [comment]
sorry i gave you incorrect instructions. It shouldnt be permission issue, just incorrect path because windows has `\\` and linux has `/` folder separation


Try this

```
destination = 'C:\\Users\\Flo\\Documents\\Piano\\hdpiano-master\\{0}\\%(title)s.%(ext)s'.format(folder_name)
```

you must be in `C:\\Users\\Flo\\Documents\\Piano\\hdpiano-master\\` folder with cmd when runing download.py

if you get error with this please give another screenshot here

**Comment by cyberpescadito** [comment]
Still the same error but python seems to not processing "%(title)s.%(ext)s" part:

![image](https://user-images.githubusercontent.com/32546144/79757049-d0e14000-831b-11ea-9c1a-96a5a4faf6b1.png)

where does come from these title and ext var? 



fyi my python version:
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32

**Comment by dcrystalj** [comment]
`%(title)s.%(ext)s` are variables for `youtube-dl` and should not be processed by python at all so this should be fine.

Check`folder_name` because looks like it is not processed correctly. Add folder_name to print in line 40 to see what names does it get. I think it should be `hes-a-pirate-...`

Also make sure you have latest `youtube-dl` installed.

**Comment by cyberpescadito** [comment]
see below in yellow: 
![image](https://user-images.githubusercontent.com/32546144/79757874-eefb7000-831c-11ea-93b6-1a66ce35724c.png)


Edit: ok I was missing the youtube-dl. sorry for that, thanks for your help.
  will suggest you a requirements.txt file mentionning all dependencies to help people installing it more easily

**Comment by dcrystalj** [comment]
please create PR for requirements.txt and also `windows` `linux` path handling.
